codecov scripts

diff --git a/.github/workflows/test_coverage_on_merge.yml b/.github/workflows/test_coverage_on_merge.yml
--- a/.github/workflows/test_coverage_on_merge.yml
+++ b/.github/workflows/test_coverage_on_merge.yml
@@ -61,11 +61,19 @@ jobs:
           
               dart pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '.g.dart$' -r '.gr.dart$' -r '.freezed.dart$' -r '.i69n.dart$' -r 'di_initializer.config.dart'
           
-              # Move coverage file to unique name
+              echo 'Renaming coverage file...'
               mv coverage/lcov.info coverage/lcov_${MELOS_PACKAGE_NAME}.info
+              if [ $? -eq 0 ]; then
+                echo 'Coverage file renamed to coverage/lcov_${MELOS_PACKAGE_NAME}.info'
+              else
+                echo 'Failed to rename coverage file'
+              fi
+              
+              echo 'Listing coverage directory:'
+              ls -l coverage/
           
               cd $GITHUB_WORKSPACE
-              ./codecov --verbose upload-process --fail-on-error -t ${{ secrets.CODECOV_TOKEN }} -f coverage/lcov_${MELOS_PACKAGE_NAME}.info -F MELOS_PACKAGE_NAME --disable-search
+              ./codecov --verbose upload-process --fail-on-error -t ${{ secrets.CODECOV_TOKEN }} -f coverage/lcov_${{ MELOS_PACKAGE_NAME }}.info -F MELOS_PACKAGE_NAME --disable-search
             fi"
 
 #      - name: 📝 Preparing coverage report
